# Generated by Django 4.2 on 2023-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
