# Generated by Django 4.2 on 2023-10-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecomadmin', '0004_alter_adminuser_id_alter_customeruser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.customuser'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='customuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customuser_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.customuser'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.customuser'),
        ),
    ]
